# Minimal settings for development and for ModelManager to pick up model configs
prompt_builder:
  # Directory (relative to PROJECT_ROOT) where prompt YAML templates are stored
  templates_dir: prompts/prompt_files

mcp:
  weather:
    base_url: "https://api.openweathermap.org/data/2.5/weather"
    api_key: "6857620b61dbecab1900a512355c85b0"
    module: "weather_service"
    port: 8000
    server_url: "http://localhost:8000/mcp"
    tool_name: get_weather
  time:
    module: "time_service"
    port: 8001
    server_url: "http://localhost:8001/mcp"
    tool_name: get_time
  calc:
    module: "calc_service"
    port: 8002
    server_url: "http://localhost:8002/mcp"
    tool_name: calc
  translate:
    module: "translate_service"
    port: 8003
    server_url: "http://localhost:8003/mcp"
    tool_name: translate
  notes:
    module: "notes_service"
    port: 8004
    server_url: "http://localhost:8004/mcp"
    tool_name: add_note
  news:
    module: "news_service"
    port: 8005
    server_url: "http://localhost:8005/mcp"
    tool_name: get_headlines

models:
  WhisperMediumInfer:
    model_name: "openai/whisper-medium"
    samplerate: 16000
    device: "cpu"
  TitaNetEmbeddingInfer:
    model_name: "nvidia/speakerverification_en_titanet_large"
    sample_rate: 16000
    sample_duration: 1.0
  OpenAIWhisperTinyInfer:
    model_name: "openai/whisper-tiny"
    samplerate: 16000
  QwenV25Infer:
    model_name: "Qwen/Qwen2.5-VL-3B-Instruct"
    device: "mps"
  SentenceEmbedderInfer:
    model_name: "all-MiniLM-L6-v2"
    device: "mps"
  GLiNERInfer:
    model_name: "urchade/gliner_base"
    device: "mps"
  SpeakerEmbeddingInfer:
    model_name: "speechbrain/spkrec-ecapa-voxceleb"
  ECAPAEmbeddingInfer:
    model_name: "speechbrain/spkrec-ecapa-voxceleb"
    sample_rate: 16000

memory:
  dir: "{project_root}/.memory/"

db:
  audio_recogniser: "{project_root}/.cache/audio_embeddings.npz"

# Path (absolute or repo-relative) to a speaker embedding .npy file used by TTS.
# If empty or null, TTS will run without a speaker embedding (neutral voice).
tts:
  embedding_path: "{project_root}/artefacts/tts_kn.npy"
